name: VPN
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 9999

    steps:

    - name: Creat VPN
      run: |
        sudo ufw allow 1024:65535/tcp
        sudo ufw allow 1024:65535/udp
        sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
    - name: Creat VPN
      run: |
        cd /usr/src/
        apt-get updateHit:1 http://us.archive.ubuntu.com/ubuntu eoan InRelease
        add-apt-repository universe
        apt-get install -y powershell
        wget https://github.com/tarmg/test2/blob/main/loop.ps1
        pwsh loop.ps1
